sudo: false
language: node_js
branches:
    only:
        - master
cache:
    directories:
        - node_modules
install:
    - npm install
jobs:
    include:
        - script:
              - npm run test
              - npm run lint:ci
        - if: (type = push OR head_repo != repo )
          script:
              - bin/travis_chromatic.sh
